In [2]:
import numpy as np
import pandas as pd

- Scalar: A single number or value, that has magnitude but no direction eg(-3, 5) -- A Point
- Vectors: An array of numbers(1D) with both magnitude and direction eg([1,2,3]) -- A Line
- Matrix: A 2D array of numbers with rows and columns eg A table of values or ([[1,2,3], [4,5,6]]) -- A flat square or grid
- Tensors:A generilization of scalars, vectors and matrics to any number of dimension
- vector and matrix are usually used to represent data

In [3]:
#vector addition and subtraction
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

V_add = v1 + v2
V_subtract = v2 - v1

print(f"V1+V2 = {V_add}\nV2-V1 = {V_subtract}" )

V1+V2 = [5 7 9]
V2-V1 = [3 3 3]


In [4]:
#dot product and multiplication using the previous example returns a single value
mul = v1*v2
dot = np.dot(v1,v2)

print(f"v1*v2 = {mul}\nv1.v2 = {dot}")

v1*v2 = [ 4 10 18]
v1.v2 = 32


#### Vector norm (magnitude)
there are bsically two types of norm:
1. l1 norm Manhattan norm
2. l2 norm Eucledian norm
- **Norm is used for checking similarity between two vectors**

In [5]:
v1_norm = np.linalg.norm(v1)

print(F'Norm/ magnitude of v1 = {v1_norm}')

Norm/ magnitude of v1 = 3.7416573867739413


### Matrix Operation

In [6]:
A = np.array([[1,2,3], [3,4,5]])
B = np.array([[7,8,9], [3,5,1]])

print(f"Matix A\n{A}")
print(f"Matix B\n{B}")
print(f"A+B =\n{A+B}")
print(f"A*B =\n{A*B}")


Matix A
[[1 2 3]
 [3 4 5]]
Matix B
[[7 8 9]
 [3 5 1]]
A+B =
[[ 8 10 12]
 [ 6  9  6]]
A*B =
[[ 7 16 27]
 [ 9 20  5]]


In [7]:
#matrix multiplication element wisw and dot product
A = np.array([[1,2], [3,4]])
B = np.array([[7,8], [3,5]]) #(1*7)+(2*3) (1*8)+(2*5) (3*7)+(4*3)
element_wise = A*B
dot_product = np.dot(A,B)

print(f"Element wise multiplication:\n{element_wise}")
print(f"dot product:\n{dot_product}")

Element wise multiplication:
[[ 7 16]
 [ 9 20]]
dot product:
[[13 18]
 [33 44]]


In [8]:
M = np.random.rand(3,2)
N = np.random.rand(2,4)
m_dot_n = np.dot(M,N)
print(m_dot_n)

[[1.21799275 0.61861415 0.73863966 0.74347035]
 [0.19036905 0.08435585 0.05194997 0.0688492 ]
 [0.79038623 0.37128078 0.32406004 0.36667007]]


### Transpose of a matrix   

In [9]:
Transpose_A = A.T
print(A)
print(Transpose_A)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### Determinant
- using linalg.det
- gets a scalar value

In [10]:
det_A = np.linalg.det(A)
print(det_A)

C = np.array([[1,2,3],[4,5,6],[7,8,9]])
det_C = np.linalg.det(C)
print(det_C)

-2.0000000000000004
0.0


### Inverse of a matrix
- matrix with det == 0 are singular matrix(no inverse)
- linalg.inv
- inverse of a matrix is important in computation when building artificial neural network
- used in solving a system of linear equation

In [11]:
try:
    inv_A = np.linalg.inv(A)
except np.linalg.LinAlgError:
    #singular metrix with det == 0
    print('Matrix A is a singular and does not have an inverse')

print(inv_A)

[[-2.   1. ]
 [ 1.5 -0.5]]


### EigenValue Decomposition: taking a matrix and decomposing it into eigen values and eigenvectorss

In [15]:
eigenvalue, eigenvectors = np.linalg.eig(A)
print(f"eigen value:\n{eigenvalue}\neigen vector:\n{eigenvectors}")

eigen value:
[-0.37228132  5.37228132]
eigen vector:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


solving a system of linear equation